apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-container
        imagePullPolicy: IfNotPresent
        image: auth
        resources:
          limits:
            memory: "512Mi"
            cpu: "2000m"
          requests:
            memory: "256Mi"
            cpu: "1000m"
        env:
        - name: AUTH_MONGO_URI
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: AUTH_MONGO_URI

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: JWT_SECRET

        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: GOOGLE_CLIENT_ID

        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: GOOGLE_CLIENT_SECRET

        - name: GOOGLE_CALLBACK_URL
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: GOOGLE_CALLBACK_URL
        - name: BREVO_API_KEY
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: BREVO_API_KEY
        - name: BREVO_SENDER_EMAIL
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: BREVO_SENDER_EMAIL
        
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /api/readyz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
        ports:
        - containerPort: 3000
