apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codespace-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/sandbox
        pathType: Prefix

        backend:
          service:
            name: sandbox-service
            port:
              number: 80