apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-deployment
  labels:
    name: sandbox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      serviceAccountName: resource-manager
      containers:
      - image: sandbox:v1
        imagePullPolicy: IfNotPresent
        name: main-sandbox-container
        resources:
          limits:
            memory: "1Gi"
            cpu: "2000m"
          requests:
            memory: "512Mi"
            cpu: "1000m"
        env:
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: redis
        livenessProbe:
          httpGet:
            path: /api/sandbox/healthz
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/sandbox/readyz
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
        ports:
        - containerPort: 3000
